import turtle
window = turtle.Screen()
t = turtle.Pen()
t.shape('turtle')
t.pensize(5)
t.forward(300)
t.penup()
t.forward(20)
t.left(90)
t.forward(50)
t.pendown()
t.forward(100)
t.penup()
t.forward(20)
t.left(90)
t.forward(50)
t.pendown()
t.forward(300)
t.penup()
t.forward(20)
t.left(90)
t.forward(50)
t.pendown()
t.forward(100)
t.penup()
t.forward(20)
t.left(90)
t.forward(50)
t.pendown()