print('Введи число: ')
Number1 = int(input())
print('Введите ещё одно число: ')
Number2 = int(input())
print(Number1 + Number2)
print(Number1 * Number2)
print(Number1 / Number2)
print(Number1 - Number2)
